[package]
name = "jira-at-home"
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
publish = false
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
clap.workspace = true
dirs.workspace = true
libmcp.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true

[dev-dependencies]
libmcp-testkit = { git = "https://git.swarm.moe/libmcp.git", rev = "6d9e1c1a1f123a57e0bcb152a7c992154661577e", package = "libmcp-testkit" }

[lints]
workspace = true
